module.exports.userService = require('./user.service')
module.exports.roleService = require('./role.service')
module.exports.peopleService = require('./people.service')
module.exports.priceService = require('./price.service')
module.exports.billService = require('./bill.service')
module.exports.roomService = require('./room.service')
module.exports.contractService = require('./contract.service')
module.exports.redisService = require('./redis.service')
