export const FETCH_PEOPLE_ACTION = 'app/People/FETCH_PEOPLE_ACTION'
export const FETCH_PEOPLE_SUCCESS_ACTION = 'app/People/FETCH_PEOPLE_SUCCESS_ACTION'
export const REMOVE_PEOPLE_ACTION = 'app/People/REMOVE_PEOPLE_ACTION'
export const CREATE_REGISTRATION_TOKEN = 'app/People/CREATE_REGISTRATION_TOKEN'
