export const FETCH_PEOPLE_ACTION = 'app/People/FETCH_PEOPLE_ACTION'
export const FETCH_PEOPLE_SUCCESS_ACTION = 'app/People/FETCH_PEOPLE_SUCCESS_ACTION'
export const REMOVE_PEOPLE_ACTION = 'app/People/REMOVE_PEOPLE_ACTION'

export const NEW_REGISTRATION_TOKEN = 'app/People/NEW_REGISTRATION_TOKEN'
export const GET_REGISTRATION_TOKEN_SUCCESS = 'app/People/GET_REGISTRATION_TOKEN_SUCCESS'
export const GET_REGISTRATION_TOKEN = 'app/People/GET_REGISTRATION_TOKEN'
export const REMOVE_REGISTRATION_TOKEN = 'app/People/REMOVE_REGISTRATION_TOKEN'
